steps:
  # Step 1: Ensure dependencies are downloaded
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['dependency:resolve']
    dir: 'ProCounsellor'

  # Step 2: Build the JAR file (Using Java 17)
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-DskipTests']
    dir: 'ProCounsellor'
    env:
      - 'JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64'

  # Step 3: Build Docker image (Fixed directory context)
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/procounsellor-backend-repo/backend:$COMMIT_SHA'
      - '-f'
      - 'ProCounsellor/Dockerfile'   # Explicitly specify the Dockerfile
      - 'ProCounsellor/'             # Set the correct context directory

  # Step 4: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/procounsellor-backend-repo/backend:$COMMIT_SHA'

  # Step 5: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'run'
      - 'deploy'
      - 'procounsellor-backend'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/procounsellor-backend-repo/backend:$COMMIT_SHA'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--max-instances=3'

substitutions:
  _PROJECT_ID: "procounsellor-71824"

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/procounsellor-backend-repo/backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
